title: Ilia Viazov  # You can add your name here

logo: 1.png # Use a relative path to logo image 

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin
background:
  color: green
